// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCM7vev4YT0sqUt1lwYunz4KcKcfrraekY',
    appId: '1:522214453402:web:69a402c856fb580dacef23',
    messagingSenderId: '522214453402',
    projectId: 'hackjam-c3718',
    authDomain: 'hackjam-c3718.firebaseapp.com',
    storageBucket: 'hackjam-c3718.firebasestorage.app',
    measurementId: 'G-P4G89B42MK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRv1BIwH2RJLNGczISnyYUihS6-QetsYI',
    appId: '1:522214453402:android:1e15f7a85c3b864cacef23',
    messagingSenderId: '522214453402',
    projectId: 'hackjam-c3718',
    storageBucket: 'hackjam-c3718.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5HKshsEGtprt0s-yQdh4NEKztIxCYvc4',
    appId: '1:522214453402:ios:8324ecb3a9eb80f8acef23',
    messagingSenderId: '522214453402',
    projectId: 'hackjam-c3718',
    storageBucket: 'hackjam-c3718.firebasestorage.app',
    iosBundleId: 'com.example.isj2AndroidFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCM7vev4YT0sqUt1lwYunz4KcKcfrraekY',
    appId: '1:522214453402:web:ae406bd2f233e1bdacef23',
    messagingSenderId: '522214453402',
    projectId: 'hackjam-c3718',
    authDomain: 'hackjam-c3718.firebaseapp.com',
    storageBucket: 'hackjam-c3718.firebasestorage.app',
    measurementId: 'G-63TK4RD8H9',
  );
}
